name: Push to main
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses:
          actions/checkout@v2
      - name: run tests
        run: npm test
        shell: bash
      - name: Send Test results to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
